# Generated by Django 2.1.7 on 2019-03-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='commerce.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderDetails',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='commerce.OrderDetails'),
            preserve_default=False,
        ),
    ]
