# Generated by Django 2.1.7 on 2019-03-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20190311_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.UUIDField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='personalInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.User'),
        ),
    ]
