# Generated by Django 2.1.7 on 2019-03-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
    ]
